### ISSUE TITLE
`env::args().collect()` doesn't work on it's own because `[String]` doesn't have a constant size

### ISSUE THREAD

**Issue by joelself** [zcdziura/pirate#3]
I was following the examples in the README and had this in my code:

``` rust
let matches: Matches = match matches(&env::args().collect(), &mut vars) {
    Ok(m) => m,
    Err(e) => {
      println!("Error: {}", e);
      usage(&vars);
      return;
    }
  };
```

But that was giving me these errors:

``` bash
src/bin/tomlkit.rs:37:53: 37:60 error: the trait bound `[std::string::String]: std::marker::Sized` is not satisfied [E0277]
src/bin/tomlkit.rs:37   let matches: Matches = match matches(&env::args().collect(), &mut vars) {
                                                                          ^~~~~~~
src/bin/tomlkit.rs:37:53: 37:60 help: run `rustc --explain E0277` to see a detailed explanation
src/bin/tomlkit.rs:37:53: 37:60 note: `[std::string::String]` does not have a constant size known at compile-time
src/bin/tomlkit.rs:37:53: 37:60 error: the trait bound `[std::string::String]: std::iter::FromIterator<std::string::String>` is not satisfied [E0277]
src/bin/tomlkit.rs:37   let matches: Matches = match matches(&env::args().collect(), &mut vars) {
                                                                          ^~~~~~~
src/bin/tomlkit.rs:37:53: 37:60 help: run `rustc --explain E0277` to see a detailed explanation
src/bin/tomlkit.rs:37:53: 37:60 note: a collection of type `[std::string::String]` cannot be built from an iterator over elements of type `std::string::String`
error: aborting due to 2 previous errors
```

Looks like `collect()` defaults to creating an array and you can't create an array of `String`s because they don't have a fixed size known at compile time. Instead I did this:

``` rust
  let args: Vec<String> = env::args().collect();
  let matches: Matches = match matches(&args, &mut vars) {
```

This is on rustc 1.9.0-beta.2 (87cb73304 2016-05-04) and rustc 1.8.0-beta.1 (facbfdd71 2016-03-02) (the error messages are a little different between versions).

**Comment by zcdziura** [comment]
Very interesting... When originally writing this library, I had run into a similar issue. I thought that I had fixed it, but apparently I hadn't updated the documentation to resolve that!

If you'd like, go ahead and submit a pull request to fix the documentation, reflecting your solution to the problem. I'll have a look over tonight and merge it in.

I should probably also have a look-through of the code and relevant docs and do a bit of spring cleaning. It's been a while since I last looked at this library, and it's pretty clear that it was an "honest first attempt". It's also clear that I didn't update the documentation properly.

Thank you for keen eye! I appreciate knowing that someone knows that this library exists still! ;)

**Comment by joelself** [comment]
It's really easy to get up and running parsing and displaying command line arguments. However, it's missing a key feature that I think will turn off most people: positional arguments. There's a few improvements I'd like to see, but I'll probably make them myself.
